<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Component</h1>

<form class="pure-form" method="get" action="/component/<?=$component->getId()?>/updat">
    <label for="id" >ID</label>
    <input name="id" id="id" type="text" size="60" value="<?=$component->getId()?>" /><br />
    <label for="name">Component</label>
       <input name="component" id="component" type="text" size="60"  value="<?=$component->getName()?>"/><br />
    <input type="submit" class="pure-button" value="Update" />
</form>
<?php require 'footer.php' ?>
</body>
</html>


